# Generated by Django 3.0.7 on 2021-04-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='quantity',
            new_name='amount',
        ),
    ]
