# Generated by Django 3.0.7 on 2022-04-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, null=True)),
                ('age', models.CharField(max_length=40, null=True)),
                ('phonenumber', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
